services:
  - type: web
    name: pinterest-backend
    runtime: python
    rootDir: BACKEND
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    plan: free
    pythonVersion: "3.12.0"
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 60
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_REGION
        value: us-east-1
      - key: AWS_S3_BUCKET
        value: pinterests3uide
      - key: PRESIGNED_URL_EXPIRATION
        value: 3600
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: ALLOWED_ORIGINS
        value: "http://localhost:5173,http://127.0.0.1:5173,https://pinterest-clone-pi-snowy.vercel.app"
